
CREATE TABLE PRICES
(
    BRAND_ID    BIGINT          NOT NULL,
    START_DATE  TIMESTAMP       NOT NULL,
    END_DATE    TIMESTAMP       NOT NULL,
    PRICE_LIST  INTEGER         NOT NULL,
    PRODUCT_ID  BIGINT          NOT NULL,
    PRIORITY    SMALLINT        NOT NULL,
    PRICE       NUMERIC(20,2)   NOT NULL,
    CURRENCY    CHAR(3)         NOT NULL
);

CREATE TABLE BRANDS
(
    ID    BIGINT          NOT NULL CONSTRAINT BRANDS_PK PRIMARY KEY,
    NAME  VARCHAR(255)    NOT NULL
);

ALTER TABLE PRICES ADD FOREIGN KEY (BRAND_ID_FK) REFERENCES BRANDS(ID);
